name: first_action
on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
    branches:
      - main  # Trigger this workflow: when a PR is opened with main as target

  push:
    branches:
      # - main
      - 'dev-*' 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "Hi, this is the first step"
      - name: checkout Code
        uses: actions/checkout@v2
      - name: install_pandas
        run: pip install pandas
      - name: run_python
        run: python main.py
      - name: list items
        run: ls -ll
